CREATE TABLE emergencias (
    id BIGSERIAL PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    idcitizen BIGINT NOT NULL,
    fecha_ocurrio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unitID BIGINT
);