spring.application.name=123+

spring.rabbitmq.primary.host=localhost
spring.rabbitmq.primary.port=5672
spring.rabbitmq.primary.username=guest
spring.rabbitmq.primary.password=guest

sacavix.queue.getcall.name=cola1

spring.r2dbc.databases.citizensdb.url=r2dbc:postgresql://localhost:5432/citizensdb
spring.r2dbc.databases.citizensdb.username=myuser
spring.r2dbc.databases.citizensdb.password=mypassword